"""create procurement, invoice and audit tables

Revision ID: da14116678e0
Revises: 
Create Date: 2026-09-20 19:05:08.218138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import countersign.db.base


# revision identifiers, used by Alembic.
revision: str = 'da14116678e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_filename', sa.String(length=300), nullable=False),
    sa.Column('media_type', sa.String(length=80), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('intake_status', sa.String(length=40), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('normalised_name', sa.String(length=200), nullable=False),
    sa.Column('tax_id', sa.String(length=40), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_normalised_name'), 'vendors', ['normalised_name'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('parsed_payload', sa.JSON(), nullable=True),
    sa.Column('field_confidences', sa.JSON(), nullable=True),
    sa.Column('validator_failures', sa.JSON(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('extraction_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_document_id'), 'extractions', ['document_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('ordered_at', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', countersign.db.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('tax_total', countersign.db.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('total', countersign.db.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('delivery_note_number', sa.String(length=40), nullable=False),
    sa.Column('po_id', sa.String(length=36), nullable=False),
    sa.Column('delivered_at', sa.Date(), nullable=False),
    sa.Column('received_by', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_note_number')
    )
    op.create_index(op.f('ix_deliveries_po_id'), 'deliveries', ['po_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('po_id', sa.String(length=36), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('subtotal', countersign.db.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('tax_total', countersign.db.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('total', countersign.db.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_document_id'), 'invoices', ['document_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_po_id'), 'invoices', ['po_id'], unique=False)
    op.create_index(op.f('ix_invoices_state'), 'invoices', ['state'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False)
    op.create_table('po_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('po_id', sa.String(length=36), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('uom', sa.String(length=12), nullable=False),
    sa.Column('quantity', countersign.db.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', countersign.db.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('line_total', countersign.db.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate', countersign.db.base.Money(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_id', 'line_no')
    )
    op.create_index(op.f('ix_po_lines_po_id'), 'po_lines', ['po_id'], unique=False)
    op.create_index(op.f('ix_po_lines_sku'), 'po_lines', ['sku'], unique=False)
    op.create_table('delivery_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('delivery_id', sa.String(length=36), nullable=False),
    sa.Column('po_line_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_received', countersign.db.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_lines_delivery_id'), 'delivery_lines', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_lines_po_line_id'), 'delivery_lines', ['po_line_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('uom', sa.String(length=12), nullable=True),
    sa.Column('quantity', countersign.db.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', countersign.db.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('line_total', countersign.db.base.Money(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate', countersign.db.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('matched_po_line_id', sa.String(length=36), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['matched_po_line_id'], ['po_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'line_no')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_sku'), 'invoice_lines', ['sku'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('agent_version', sa.String(length=20), nullable=False),
    sa.Column('steps_used', sa.Integer(), nullable=True),
    sa.Column('tool_calls_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_invoice_id'), 'recommendations', ['invoice_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_invoice_id'), 'approvals', ['invoice_id'], unique=False)
    op.create_table('check_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('check_code', sa.String(length=40), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('invoice_line_id', sa.String(length=36), nullable=True),
    sa.Column('observed', countersign.db.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('expected', countersign.db.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('tolerance', countersign.db.base.Money(precision=18, scale=4), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['invoice_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_results_check_code'), 'check_results', ['check_code'], unique=False)
    op.create_index(op.f('ix_check_results_invoice_id'), 'check_results', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_check_results_outcome'), 'check_results', ['outcome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_results_outcome'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_invoice_id'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_check_code'), table_name='check_results')
    op.drop_table('check_results')
    op.drop_index(op.f('ix_approvals_invoice_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_recommendations_invoice_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_invoice_lines_sku'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_delivery_lines_po_line_id'), table_name='delivery_lines')
    op.drop_index(op.f('ix_delivery_lines_delivery_id'), table_name='delivery_lines')
    op.drop_table('delivery_lines')
    op.drop_index(op.f('ix_po_lines_sku'), table_name='po_lines')
    op.drop_index(op.f('ix_po_lines_po_id'), table_name='po_lines')
    op.drop_table('po_lines')
    op.drop_index(op.f('ix_invoices_vendor_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_state'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_po_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_document_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_deliveries_po_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_extractions_document_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_vendors_normalised_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
